services:
  raid-web:
    build: .
    image: raid-app:latest
    volumes:
      - raids-data:/data
#    ports:
#      - "8000:8000"
    networks:
      - wtb-shared
    restart: unless-stopped

volumes:
  raids-data:
    external: false

networks:
  wtb-shared:
    external: true
